-- Supabase SQL Schema for Kaalchakra (Phase 1 MVP)

-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. STOCKS TABLE
CREATE TABLE IF NOT EXISTS public.stocks (
    symbol TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    sector TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.stocks ENABLE ROW LEVEL SECURITY;

-- Allow read access to anyone (authenticated or anonymous)
CREATE POLICY "Allow public read access to stocks" 
    ON public.stocks FOR SELECT 
    USING (true);

-- 2. DAILY PRICES TABLE
CREATE TABLE IF NOT EXISTS public.daily_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT REFERENCES public.stocks(symbol) ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL,
    open NUMERIC NOT NULL,
    high NUMERIC NOT NULL,
    low NUMERIC NOT NULL,
    close NUMERIC NOT NULL,
    volume BIGINT NOT NULL,
    rsi NUMERIC,
    sma_20 NUMERIC,
    sma_50 NUMERIC,
    sma_200 NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_symbol_date UNIQUE (symbol, date)
);

-- Enable RLS
ALTER TABLE public.daily_prices ENABLE ROW LEVEL SECURITY;

-- Allow read access to anyone
CREATE POLICY "Allow public read access to daily_prices" 
    ON public.daily_prices FOR SELECT 
    USING (true);

-- Indexing for fast queries
CREATE INDEX IF NOT EXISTS idx_daily_prices_symbol_date ON public.daily_prices(symbol, date DESC);
CREATE INDEX IF NOT EXISTS idx_daily_prices_date ON public.daily_prices(date DESC);

-- 3. WATCHLISTS TABLE
CREATE TABLE IF NOT EXISTS public.watchlists (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    symbol TEXT REFERENCES public.stocks(symbol) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_user_symbol UNIQUE (user_id, symbol)
);

-- Enable RLS
ALTER TABLE public.watchlists ENABLE ROW LEVEL SECURITY;

-- Allow users to manage their own watchlists
CREATE POLICY "Allow users to view their own watchlist" 
    ON public.watchlists FOR SELECT 
    USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert into their own watchlist" 
    ON public.watchlists FOR INSERT 
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to delete from their own watchlist" 
    ON public.watchlists FOR DELETE 
    USING (auth.uid() = user_id);

-- 4. WAITLIST TABLE (For Landing Page Signups)
CREATE TABLE IF NOT EXISTS public.waitlist (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- Allow anonymous inserts (for landing page signups)
CREATE POLICY "Allow anonymous waitlist signups" 
    ON public.waitlist FOR INSERT 
    WITH CHECK (true);

-- Only allow authenticated admin reads (if any)
CREATE POLICY "Allow admin read access to waitlist" 
    ON public.waitlist FOR SELECT 
    USING (auth.role() = 'service_role');

-- 5. PLANS TABLE
CREATE TABLE IF NOT EXISTS public.plans (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    currency TEXT DEFAULT 'INR' NOT NULL,
    interval TEXT NOT NULL
);

-- Enable RLS
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;

-- Allow public read access to plans
CREATE POLICY "Allow public read access to plans" 
    ON public.plans FOR SELECT 
    USING (true);

-- 6. SUBSCRIPTIONS TABLE
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,
    plan_id TEXT REFERENCES public.plans(id) NOT NULL,
    status TEXT NOT NULL,
    razorpay_subscription_id TEXT UNIQUE,
    current_period_end TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own subscription
CREATE POLICY "Allow users to view their own subscription" 
    ON public.subscriptions FOR SELECT 
    USING (auth.uid() = user_id);

-- Seed Plans
INSERT INTO public.plans (id, name, price, currency, interval)
VALUES 
    ('pro_monthly', 'Pro Monthly Plan', 499, 'INR', 'month')
ON CONFLICT (id) DO UPDATE 
SET name = EXCLUDED.name, price = EXCLUDED.price;
